#!/usr/bin/env python3

import sys
import os
import argparse

sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), './../'))
from src.verses.scanner import VerseScanner
from src.verses.parser import VerseParser
from src.verses.generator import VerseGenerator
from src.verses.nodes import NodeVerse
from src.verses.errors import ParseError
from src.words.splitter import WordSplitter
from src.stress.finder import StressFinder

help_verse  = 'O verso que será metrificado.'
help_help   = 'Mostra essa mensagem e sai.'
help_noline = 'Não insere o caractere de nova linha no final da saída.'

argparser = argparse.ArgumentParser(description='', add_help=False)
argparser.add_argument('verse', type=str, help=help_verse)
argparser.add_argument('-N', '--noline', action='store_true', help=help_noline)
argparser.add_argument('-h', '--help', action='help', help=help_help)



def print_output(output: str, noline: bool):
    if noline:
        print(output, end="")
    else:
        print(output)


def main():
    args         = argparser.parse_args()
    text: str    = args.verse
    noline: bool = args.noline

    text      = text.lower().strip()

    scanner   = VerseScanner(text)
    parser    = VerseParser(scanner)
    splitter  = WordSplitter()
    finder    = StressFinder()
    generator = VerseGenerator(splitter, finder)

    verse: NodeVerse
    try:
        verse = parser.parse()
    except ParseError as error:
        index = error.index
        chars = list(text)
        chars.insert(index, '*')
        text  = ''.join(chars)
        print_output(text, noline)
        exit(1)
    except:
        print_output(text, noline)
        exit(2)

    output: str = ''
    try:
        output = generator.run(verse)
    except:
        print_output(f'{text}**', noline)

    print_output(output, noline)


if __name__ == '__main__':
    main()
